/* 
	File written entirely by Nate H - don't be scared to ask questions, this wasn't autogenerated!

	As of Apr 6, 2023, though we plan to change up the behavior a little bit, 
	the file currently defines the endpoint for /descriptions,
	specifically the get & post request behavior.
*/

const { response } = require('express');
var express = require('express');
const { getAllOpps } = require('../models/getAllOpps.model');
const { postDesc } = require('../models/postDesc.model');

var router = express.Router();

router.get('/', function(req, res, next) {

});

router.post("/", function(req, res, next){
	if(req.session.perms == 0)
	{
		var promise = postDesc(req);
		promise.then(function(desc){
			console.log("This is actually sending");
			res.json(desc);
		},
		   function(error) {
		   res.status(503).send(error);
		});
	}
	else
	{
		res.status(403).send("You're not authorized to post new descs!");
	}
});

module.exports = router;